/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mips.simulator;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static mips.simulator.AssemblerGui.obj;


public class SimulatorGUI extends javax.swing.JFrame {

    int programCounter = 0;
    Simulator sim = new Simulator(obj);
    DefaultTableModel modelRegisters;
    DefaultTableModel modelMemory;
    DefaultTableModel modelInf;
    
    public SimulatorGUI() {
        initComponents();
        modelRegisters = (DefaultTableModel) tableRegisters.getModel();
        modelMemory = (DefaultTableModel) tableMemory.getModel();
        modelInf = (DefaultTableModel) tableInf.getModel();
        //fill Registers
        updateRegisters();
        //fill Used Memories
        int pos = 0;
        for(int i=0 ; i<obj.Instructions.size() ;++i){
            if(!obj.Instructions.get(i).set.contains(":")){
                modelMemory.insertRow(tableMemory.getRowCount(), new Object[]{ obj.Decimalto8Hexa(pos),obj.Instructions.get(i).set, obj.Instructions.get(i).hexaCode} );
                //Memories.put(obj.Decimalto8Hexa(pos), obj.Instructions.get(i).set);
                pos+=4;
            }
            userCode.setText(userCode.getText() + obj.Instructions.get(i).set + "\n");
        }
        //fill kernel text segment
        for (int i = 0; i<sim.kernelSet.size(); i++) {
            textKernel.setText( textKernel.getText() + sim.kernelSet.get(i).set+ "\n");
        }
    }
    
    public void fillBinaryInf(){
        //op rs rt rd shamt funct imm addr
        char type = obj.Instructions.get(programCounter-1).type;
        ArrayList<String> bin = obj.Instructions.get(programCounter-1).Binary;
        modelInf.setRowCount(0);
        if(type == 'R'){
            modelInf.insertRow(tableInf.getRowCount(), new Object[]{ bin.get(0), bin.get(1), bin.get(2), bin.get(3), bin.get(4), bin.get(5), "", ""});
        }
        else if(type == 'I'){
            modelInf.insertRow(tableInf.getRowCount(), new Object[]{ bin.get(0), bin.get(1), bin.get(2), "", "", "", bin.get(3), ""});
        }
        else if(type == 'J'){
            modelInf.insertRow(tableInf.getRowCount(), new Object[]{ bin.get(0), "", "", "", "", "", "", bin.get(1)});
        }
    }
    
    public void updateMemories(){
        modelMemory.setRowCount(0);
        //User data segment
        int pos = 0;
        for(int i=0 ; i<obj.Instructions.size() ;++i){
            if(!obj.Instructions.get(i).set.contains(":")){
                modelMemory.insertRow(tableMemory.getRowCount(), new Object[]{ obj.Decimalto8Hexa(pos),obj.Instructions.get(i).set, obj.Instructions.get(i).hexaCode} );
                //Memories.put(obj.Decimalto8Hexa(pos), obj.Instructions.get(i).set);
                pos+=4;
            }
        }
        //data memory
        for(String i : sim.Memories.keySet()){
            modelMemory.insertRow(tableMemory.getRowCount(), new Object[]{ i,sim.Memories.get(i), obj.Decimalto8Hexa(sim.Memories.get(i))} );
        }
    }
    
    public void updateRegisters(){
        modelRegisters.setRowCount(0);
        int count = 0;
        for(int i =0 ; i<obj.Resgisters.size();++i){
            modelRegisters.insertRow(tableRegisters.getRowCount(), new Object[]{ count, obj.Resgisters.get(i), Integer.toHexString(sim.Registers.get(obj.Resgisters.get(i))) } );
            count++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRegisters = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMemory = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableInf = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        textKernel = new javax.swing.JTextArea();
        executeCurrent = new javax.swing.JButton();
        executeAll = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        counter = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        currentIns = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        userCode = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        textType = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulator");

        tableRegisters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num", "Register", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableRegisters);
        if (tableRegisters.getColumnModel().getColumnCount() > 0) {
            tableRegisters.getColumnModel().getColumn(0).setMaxWidth(40);
            tableRegisters.getColumnModel().getColumn(1).setMaxWidth(70);
            tableRegisters.getColumnModel().getColumn(2).setResizable(false);
        }

        tableMemory.setAutoCreateRowSorter(true);
        tableMemory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Location", "Content", "HexaCode"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableMemory);
        if (tableMemory.getColumnModel().getColumnCount() > 0) {
            tableMemory.getColumnModel().getColumn(0).setResizable(false);
            tableMemory.getColumnModel().getColumn(1).setResizable(false);
            tableMemory.getColumnModel().getColumn(2).setResizable(false);
        }

        tableInf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "op", "rs", "rt", "rd", "shamt", "funct", "immediate", "address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableInf);
        if (tableInf.getColumnModel().getColumnCount() > 0) {
            tableInf.getColumnModel().getColumn(0).setMaxWidth(60);
            tableInf.getColumnModel().getColumn(1).setMaxWidth(60);
            tableInf.getColumnModel().getColumn(2).setMaxWidth(60);
            tableInf.getColumnModel().getColumn(3).setMaxWidth(60);
            tableInf.getColumnModel().getColumn(4).setMaxWidth(60);
            tableInf.getColumnModel().getColumn(5).setMaxWidth(60);
        }

        textKernel.setEditable(false);
        textKernel.setColumns(20);
        textKernel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textKernel.setRows(5);
        jScrollPane4.setViewportView(textKernel);

        executeCurrent.setText("Execute current line");
        executeCurrent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeCurrentActionPerformed(evt);
            }
        });

        executeAll.setText("Execute all");
        executeAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeAllActionPerformed(evt);
            }
        });

        jLabel1.setText("program counter : ");

        counter.setEditable(false);
        counter.setText("0");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Registers");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Kernel Text Segment");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Memory");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Currently executing instruction");

        currentIns.setEditable(false);

        jButton3.setText("Clear Registers");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("User Text Segment");

        userCode.setEditable(false);
        userCode.setColumns(20);
        userCode.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        userCode.setRows(5);
        jScrollPane5.setViewportView(userCode);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("type");

        textType.setEditable(false);
        textType.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButton3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(executeAll, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(executeCurrent)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(currentIns, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(textType, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(counter, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                        .addComponent(jScrollPane3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel2)
                .addGap(148, 148, 148)
                .addComponent(jLabel3)
                .addGap(232, 232, 232)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(91, 91, 91))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(executeAll, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                    .addComponent(executeCurrent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(counter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(currentIns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        sim.clearRegisters();
        updateRegisters();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void executeCurrentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeCurrentActionPerformed
        // TODO add your handling code here:
        if(programCounter == sim.kernelSet.size()){
            JOptionPane.showMessageDialog(null, "Program already fully executed");
            return;
        }
        sim.runInstruction(sim.kernelSet.get(programCounter));
        programCounter++;
        counter.setText(Integer.toString(programCounter));
        updateRegisters();
        updateMemories();
        currentIns.setText(sim.kernelSet.get(programCounter-1).set);
        textType.setText(sim.kernelSet.get(programCounter-1).type +"-type");
        fillBinaryInf();
    }//GEN-LAST:event_executeCurrentActionPerformed

    private void executeAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeAllActionPerformed
        // TODO add your handling code here:
        sim.clearMemories();
        sim.clearRegisters();
        for(int i=0 ; i<sim.kernelSet.size(); ++i){
            sim.runInstruction(sim.kernelSet.get(i));
        }
        programCounter = sim.kernelSet.size();
        counter.setText(Integer.toString(programCounter));
        updateRegisters();
        updateMemories();
        currentIns.setText(sim.kernelSet.get(sim.kernelSet.size()-1).set);
        textType.setText(sim.kernelSet.get(sim.kernelSet.size()-1).type +"-type");
        fillBinaryInf();
    }//GEN-LAST:event_executeAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimulatorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField counter;
    private javax.swing.JTextField currentIns;
    private javax.swing.JButton executeAll;
    private javax.swing.JButton executeCurrent;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tableInf;
    private javax.swing.JTable tableMemory;
    private javax.swing.JTable tableRegisters;
    private javax.swing.JTextArea textKernel;
    private javax.swing.JTextField textType;
    private javax.swing.JTextArea userCode;
    // End of variables declaration//GEN-END:variables
}
